version: '3'
services:
  broker:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run broker
    environment:
      BROKER_HOST: broker
      BROKER_PORT: 1337
      PROCESS_QUEUE_TIME: 5000
      HEALTH_PORT: 3000
    ports:
      - "3000:3000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
        interval: 30s
        timeout: 10s
        retries: 5
  publisher:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run publisher
    environment:
      BROKER_HOST: broker
      BROKER_PORT: 1337
    depends_on:
      - "broker"
  consumer1:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run consumer
    environment:
      BROKER_HOST: broker
      BROKER_PORT: 1337
    depends_on:
      - "broker"
  consumer2:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run consumer
    environment:
      BROKER_HOST: broker
      BROKER_PORT: 1337
    depends_on:
      - "broker"