version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run api
    environment:
      NUMBER_OF_SHARDS: 2
      API_PORT: 3000
    ports:
      - "3002:3000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
        interval: 30s
        timeout: 10s
        retries: 5
  broker-0:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run broker
    environment:
      BROKER_HOST: broker-0
      BROKER_PORT: 1337
      PROCESS_QUEUE_TIME: 5000
      NUMBER_OF_SHARDS: 2
      API_PORT: 3000
    ports:
      - "3000:3000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
        interval: 30s
        timeout: 10s
        retries: 5
  broker-1:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run broker
    environment:
      BROKER_HOST: broker-1
      BROKER_PORT: 1337
      PROCESS_QUEUE_TIME: 5000
      NUMBER_OF_SHARDS: 2
      API_PORT: 3000
    ports:
      - "3001:3000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
        interval: 30s
        timeout: 10s
        retries: 5
  publisher:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run publisher
    environment:
      BROKER_HOST: broker-0
      BROKER_PORT: 1337
      NUMBER_OF_SHARDS: 2
      API_PORT: 3000
      QUEUE: "colita"
    depends_on:
      - "broker-0"
      - "broker-1"
  publisher2:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run publisher
    environment:
      BROKER_HOST: broker-1
      BROKER_PORT: 1337
      NUMBER_OF_SHARDS: 2
      API_PORT: 3000
      QUEUE: "colitajr"
    depends_on:
      - "broker-0"
      - "broker-1"
  consumer1:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run consumer
    environment:
      BROKER_HOST: broker
      BROKER_PORT: 1337
      QUEUE: "colita"
      NUMBER_OF_SHARDS: 2
    depends_on:
      - "broker-0"
      - "broker-1"
  consumer2:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run consumer
    environment:
      BROKER_HOST: broker
      BROKER_PORT: 1337
      QUEUE: "colitajr"
      NUMBER_OF_SHARDS: 2
    depends_on:
      - "broker-0"
      - "broker-1"